# terraform meta config
# can be used to define any custom values
#
# (*) Following characters need to be escaped for value
# (*) @|\"'
#
infra:
  aws:
    common: &aws_common
      s3_bucket: ytensor42-common
      aws_region: us-west-2
      module_base: git\@github.com:ytensor42/demos.git//tf-modules
      account_id: 119145547444
      config_key: config
    base:
      <<: *aws_common
      tfstate_key: terraform-state/default/tfstate
      vpc_name: default
    vpn:
      awsclient:
        <<: *aws_common
        tfstate_key: terraform-state/awsclient/tfstate
        vpc_name: default
        dns_zone_name: aws.ansolute.com
        server_certificate_arn: arn:aws:acm:us-west-2:119145547444:certificate/01179300-ab59-4150-aa85-9b28d06e7941
        root_certificate_chain_arn: arn:aws:acm:us-west-2:119145547444:certificate/68a7a3f5-dfa5-4af0-8af5-0e7624abc84c
      vgw:
        <<: *aws_common
        tfstate_key: terraform-state/vgw/tfstate
      tgw:
        <<: *aws_common
        tfstate_key: terraform-state/tgw/tfstate
