# General config used for scripts and github workflows
#  - terraform meta values
#      - can be used to define any custom values
#  - ci/cd
#  - security
#  - MLOps
#
# (*) Following characters need to be escaped (\) for value
# (*) @|\"'
#
infra:
  aws:
    common: &aws_common
      s3_bucket: ytensor42-common
      aws_region: us-west-2
      module_base: git\@github.com:ytensor42/dev-sec-ops.git//tf-modules
      account_id: 119145547444
      config_key: config
    base:
      vpc:
        <<: *aws_common
        tfstate_key: terraform-state/default/tfstate
      natgw:
        <<: *aws_common
        tfstate_key: terraform-state/default/natgw/tfstate
      ssm-ep:
        <<: *aws_common
        tfstate_key: terraform-state/default/ssm-ep/tfstate
      ecr-ep:
        <<: *aws_common
        tfstate_key: terraform-state/default/ecr-ep/tfstate
    vpn:
      awsclientvpn:
        <<: *aws_common
        tfstate_key: terraform-state/awsclientvpn/tfstate
        vpc_name: default
        dns_zone_name: aws.ansolute.com
        server_certificate_arn: arn:aws:acm:us-west-2:119145547444:certificate/01179300-ab59-4150-aa85-9b28d06e7941
        root_certificate_chain_arn: arn:aws:acm:us-west-2:119145547444:certificate/68a7a3f5-dfa5-4af0-8af5-0e7624abc84c
      vgw:
        <<: *aws_common
        tfstate_key: terraform-state/vgw/tfstate
        vpc_name: default
        remote_ip_address: "73.93.186.146"
        remote_cidr_block: "172.18.0.0/16"
        vgw_secrets_name: vgw_secrets
      tgw:
        <<: *aws_common
        tfstate_key: terraform-state/tgw/tfstate
        vpc_name: default
        remote_ip_address: "73.93.186.146"
        remote_cidr_block: "172.18.0.0/16"
        tgw_secrets_name: tgw_secrets
    ec2:
      tester:
        <<: *aws_common
        tfstate_key: terraform-state/ec2/tester/tfstate
      develop:
        <<: *aws_common
        tfstate_key: terraform-state/ec2/develop/tfstate
    rds:
      devpostgres:
        <<: *aws_common
        tfstate_key: terraform-state/rds/devpostgres/tfstate
#
  gcp:
    common: &gcp_common
#
  azure:
    common: &azure_common
#
resource:
  common:
  eks1:
  ecs1:
#
mlops:
  common:
  project1:

#