# This file is an example of config-as-code.
# Not only can infrastructure and applications be defined in code,
# but their configuration settings can also be expressed as code and version-controlled in a repository.
#
# (*) Following characters need to be escaped in value
# (*) @|,\"'
#
infra:
  aws:
    base:
      module_base: git\@github.com:ytensor42/demos.git//tf-modules
      vpc_name: default
      account_id: 119145547444
      aws_region: us-west-2
      s3_bucket: ytensor42-common
      tfstate_key: terraform-state/default/tfstate
      config_key: config
