name: Terraform

on:
  workflow_dispatch:
    inputs:
      infra:
        description: 'Infrastructure'
        type: string
        default: 'infra/aws/base'
      command:
        description: 'Command'
        type: choice
        default: 'show'
        options:
        - show
        - plan
        - create
        - destroy

jobs:
  Terraform-Task:
    name: "terraform ${{ inputs.infra }} ${{ inputs.command }} @${{ github.ref }}"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: read
    steps:
      - name: Information
        id: info
        shell: bash
        run: |
          echo "infra : ${{ inputs.infra }}"
          echo "command : ${{ inputs.command }}"
          echo "Date & Time: $(date +%F_%T%Z)"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/
            infra/
            scripts/
            tf-modules/
            config.yaml
          sparse-checkout-cone-mode: false

      - name: Tools install
        uses: ./.github/actions/tools/install
        with:
          terraform: true

      - name: AWS credentials
        id: aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::119145547444:role/ytensor42-demos
          aws-region: us-west-2

#      - name: Setup GitHub for Git-Terraform
#        run: |
#          cat > ~/.netrc <<EOF
#          machine github.com
#          login ${{ secrets.GITHUB_TOKEN }}
#          password x-oauth-basic
#          EOF
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup SSH key for Git-Terraform
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.T7_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: terraform
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PATH=$PATH:${PWD}/bin:${PWD}/scripts
          cd scripts/
          generate.sh "${{ inputs.command }}" "${{ inputs.infra }}"
          terraform -chdir=../temp init
          if [[ "${{ inputs.command }}" == "show" ]]; then
            terraform -chdir=../temp show
          elif [[ "${{ inputs.command }}" == "plan" ]]; then
            terraform -chdir=../temp plan
          elif [[ "${{ inputs.command }}" == "create" ]]; then
            terraform -chdir=../temp apply -auto-approve
          elif [[ "${{ inputs.command }}" == "destroy" ]]; then
            terraform -chdir=../temp destroy -auto-approve
          else
            echo "Error: ${{ inputs.command }} Not supported command"
          fi
